name: chat_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
    # The following adds the Cupertino Icons font to your application.
    # Use with the CupertinoIcons class for iOS style icons.
  flutter_cupertino_localizations: ^1.0.1
  cupertino_icons: ^0.1.3
  flutter_bloc: ^5.0.1
  kiwi: ^0.2.0
  logger: ^0.9.1
  flutter_svg: ^0.18.1
  data_connection_checker: ^0.3.4
  intl: ^0.16.0
  shared_preferences: ^0.5.10
  permission_handler: ^5.0.1+1
  flutter_translate: ^1.6.0
  dio: ^3.0.10
  keyboard_avoider: ^0.1.2
  pull_to_refresh: ^1.6.1
  cached_network_image: ^2.3.2+1
  image_picker: ^0.6.7+11
  photo_view: ^0.10.2
  video_thumbnail: ^0.2.2
  video_player: ^0.11.0
  audioplayers: ^0.16.1
  file_picker: ^2.0.6
  google_maps_flutter: ^1.0.2
  flutter_cache_manager: ^1.4.2
  fluster: ^1.1.2
  share: ^0.6.5+2
  sprintf: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0
  build_runner:
  kiwi_generator: ^0.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/i18n/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto_Thin.ttf
          weight: 300
        - asset: assets/fonts/Roboto_Light.ttf
          weight: 400
        - asset: assets/fonts/Roboto_LightItalic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Roboto_Regular.ttf
          weight: 500
        - asset: assets/fonts/Roboto_Italic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Roboto_Medium.ttf
          weight: 600
        - asset: assets/fonts/Roboto_MediumItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Roboto_Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto_BoldItalic.ttf
          weight: 700
          style: italic
